{% set name = "google-geo-type" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 07643239de07bce3bd74e03a8b35542a65a600e0a9c0c8693aacb5b2e39a7184

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core-grpc >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - proto-plus >=1.22.3,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.geo.type
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-geo-type
  summary: Google Geo Type API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ytausch
